### ISSUE TITLE
use Lazy Vim

### ISSUE THREAD

**Issue by madchickenisreal** [aiken-lang/editor-integration-nvim#3]
how to use the plugin with Lazy vim?

**Comment by waalge** [comment]
Its the same for any Plug to Lazy.nvim plugin.

If you're using the starter pack, then add it here https://github.com/LazyVim/starter/blob/92b2689e6f11004e65376e84912e61b9e6c58827/lua/plugins/example.lua#L3 
Just like example on line 13

**Comment by rvcas** [comment]
I recommend just using the nvm-lspconfig stuff that got merged recently

**Comment by waalge** [comment]
Can you make that more explicit. Docs still point at this repo
https://aiken-lang.org/installation-instructions#editor-integrations

Edit: Are you saying that this repo has been superseded and should be deprecated, or is it complementary?

**Comment by rvcas** [comment]
@waalge it's still useful, but once tree-sitter is done nvim can also highlight using that. More recently, you don't necessarily need a dedicated plugin for languages in nvim. Just tree-sitter and lspconfig is enough.

**Comment by KtorZ** [comment]
See https://github.com/aiken-lang/editor-integration-nvim#lazynvim
